name: log version bump

on:
  push:
    paths:
      - '**__about__.py'

jobs:
  log:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: echo version value
        run: echo "hello"
