name: log version

on:
  push:
    paths:
      - 'src/linovelib2epub/__about__.py'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            clean: false
      - uses: actions/setup-python@v2
      - name: Open Web Client Directory
        working-directory: src/linovelib2epub
        run: |
          ls -la
      # - uses: jannekem/run-python-script-action@v1
      #  with:
      #    script: |
      #      with open('../../src/linovelib2epub/__about__.py', encoding='utf8') as fd:
      #          print(fd.read())
