name: log version

on:
  push:
    paths:
      - 'src/linovelib2epub/__about__.py'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          clean: false

      - uses: actions/setup-python@v2

      - name: print version
        working-directory: src/linovelib2epub
        run: |
          cat __about__.py